name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U sphinx sphinx-rtd-theme

      - name: Build docs
        run: |
          sphinx-build -b html ./doc/source/ public
          touch public/.nojekyll

      - name: Deploy
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
